LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := WfdService
LOCAL_SRC_FILES := WfdService.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_PATH := $(TARGET_COPY_OUT_SYSTEM)/app/$(LOCAL_MODULE)
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)
